OK. No exception before invoke!
