NAME = "aio dio bugs"
AUTHOR = "Rafal Wijata <wijata@nec-labs.com>"
TEST_TYPE = "client"
TEST_CLASS = "Kernel"
TEST_CATEGORY = "Functional"
TIME = "MEDIUM"
DOC = """\
This was originally submitted to
 http://bugzilla.kernel.org/show_bug.cgi?id=6831 by 
Rafal Wijata <wijata@nec-labs.com>.  It caught a race in dio aio completion
that would call aio_complete() before the dio callers would update i_size.
A stat after io_getevents() would not see the new file size.

The bug was fixed in the fs/direct-io.c completion reworking that appeared
in 2.6.20.  This test should fail on 2.6.19.
"""


job.run_test('aio_dio_bugs')
